### Create a new report
POST http://localhost:3002/reports
content-type: application/json

{
    "make": "Mustang",
    "model": "Art",
    "year": 1980,
    "mileage": 100000,
    "lng": 0,
    "lat": 0,
    "price": 500000
}
### approve a report
Patch http://localhost:3002/reports/5
content-type: application/json

{
    "approved": true
}

### signin a user
POST http://localhost:3002/auth/signin
content-type: application/json

{
    "email": "jeff2@test2.com",
    "password": "test2"
}

### Get the currently signedin user
GET  http://localhost:3002/auth/whoami

### Sign out
POST  http://localhost:3002/auth/signout

### Find a user with id
GET  http://localhost:3002/auth/2


### Find all users with a given email
GET  http://localhost:3002/auth?email=jeff@test.com


### Delete a user with id
DELETE   http://localhost:3002/auth/1


### update a user with id
PATCH  http://localhost:3002/auth/2
content-type: application/json

{
    "email": "jeff@test.com",
    "password": "test"
}