### Create a new category
POST http://localhost:3002/categories
content-type: application/json

{
    "name": "watch",
    "slug": "watch",
    "description": "watch category",
    "tagIds": [
    "2e516bb8-c7d2-441b-9168-8f0f5d2e0c93"
  ]
}


